default:
  image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test

build-debug:
  stage: build
  script:
  - dotnet build -c Debug

build-release:
  stage: build
  script:
   - dotnet build -c Release
   - dotnet publish -c Release -r win-x64 --output ./publish ./PainDropSimulation/PainDropSimulation.csproj

   - tar -czvf Game.tar.gz ./publish
  artifacts:
    paths:
      - Game.tar.gz

Test:
  stage: test
  script:
    - dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml
